name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 00 13 * * *  # 8 am CST  Every day
    - cron : 30 12 * * *  # 7:30 pm CST  Every day
    - cron : 00 11 * * 1-5 # 6  pm CST  Mon-Fri

jobs: 
 run-postman-tests: 
  runs-on: ubuntu-latest

  steps:
    - name: Checkout the code
      uses: actions/checkout@v4.2.2

    - name: Install Node.js and npm
      uses: actions/setup-node@v3.9.1
      with:
        node-version: '22'

    - name: Install newman and Htmlextra globally
      run: |
            npm install -g newman 
            npm install -g newman-reporter-htmlextra


    - name: Run the Postman Collection with newman
      run: |
          newman run 'Inwarranty-flow Collection.postman_collection.json' \
          -e QA.postman_environment.json \
          -d testdata.csv \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html

    - name: Newman Report
      if: always() #ensure thatt he archive section is going to be execute irrespective whther th eprevious tep has passed or not
      uses: actions/upload-artifact@v4.6.2
      with: 
        name: Newman Report
        path: newman/*.html

    - name: Creating github page branch
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: newman/

    - name: Send email Notification
      if: alwayas()
      uses: dawidd6/action-send-mail@v6
      with: 
         server_address: ssmtp.gmail.com 
         server_port: 465
         username: ${{ secrets.EMAIL_USERNAME }}
         password:  ${{ secrets.EMAIL_PASSWORD }}
         subject: API Test Report - Github Actions
         to: mitukumari2024@gmail.com
         from: Mitu from Github Actions <${{ secrets.EMAIL_USERNAME }}
         body: |
             Hello,
             Please find the attached html report generated adter running the \Postman test via Github Actions.
             Link to live report (Github Pages): https://mitu28.github.io/Postman-API-Automation/

             
         attachments: newman/index.html
         
         
         

        
         
    
    
          
     
    
    

        
        
      
    

    
     
